apiVersion: batch/v1
kind: Job
metadata:
  name: "{will_be_replace}"
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: create-tubes-directory
        image: 'alpine:3.7'
        args: ["mkdir", "-p", "/workspace/xebikart-ml-tubes"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      - name: download-tubes
        image: 'google/cloud-sdk:alpine'
        command: ["gsutil", "-m"]
        args: ["cp", "gs://xebikart-dataset/*.tar.gz", "xebikart-ml-tubes"]
        workingDir: /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      containers:
      - name: "{will_be_replace}"
        image: "{will_be_replace}"
        command: ["{will_be_replace}"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace
        emptyDir: {}