---

- name: "install bluetooth packages"
  apt:
    name:
      - "bluetooth"
      - "libbluetooth3"
      - "libusb-dev"
    update-cache: "yes"
    state: "present"

- name: "ensure bluetooth service is enabled"
  systemd:
    name: "bluetooth"
    enabled: "yes"

- name: "add pi to bluetooth group"
  user:
    name: "{{ user }}"
    groups: "bluetooth"
    append: "yes"

- name: "get controller pairing program"
  get_url:
    url: "http://www.pabr.org/sixlinux/sixpair.c"
    dest: "{{ user_directory }}/sixpair.c"
    mode: "0700"
  notify:
    - "compile controller pairing program"
    - "launch controller pairing program"

- name: "install controller donkey part"
  pip:
    name: "git+https://github.com/autorope/donkeypart_ps3_controller.git"
    virtualenv: "{{ user_directory }}/env"
