version: "3"

services:
  xebikart_ml:
    build:
      context: .
      dockerfile: car-ml/Dockerfile
    image: xebikart_ml
    ports:
      - 8888:8888
      - 5000:5000
      - 5900:5900
    volumes:
      - ./car-ml/workspace:/workspace
      - ./../xebikart-ml-tubes:/workspace/xebikart-ml-tubes
      - ./../xebikart-ml-runs:/workspace/mlruns