---

- name: "create directory"
  file:
    path: "{{ user_directory }}/{{ app_name }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0700"
    state: "directory"

- name: "copy sources"
  copy:
    src: "{{ role_path }}/../../../{{ app_name }}/" # ending slash only copies content inside directory, not directory itself
    dest: "{{ user_directory }}/{{ app_name }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0700"

- name: "apply configuration values"
  lineinfile:
    path: "{{ user_directory }}/{{ app_name }}/config.py"
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
  with_items:
    - key:  "CAR_ID"
      value: "{{ id }}"
    - key:  "CAR_NAME"
      value: "\"{{ name }}\""
    - key:  "STEERING_LEFT_PWM"
      value: "{{ steering_left_pwm }}"
    - key:  "STEERING_RIGHT_PWM"
      value: "{{ steering_right_pwm }}"
    - key:  "THROTTLE_FORWARD_PWM"
      value: "{{ throttle_forward_pwm }}"
    - key:  "THROTTLE_REVERSE_PWM"
      value: "{{ throttle_reverse_pwm }}"
    - key: "RABBITMQ_USERNAME"
      value: "\"{{ rabbitmq_username }}\""
    - key: "RABBITMQ_PASSWORD"
      value: "\"{{ rabbitmq_password }}\""
    - key: "RABBITMQ_HOST"
      value: "\"{{ rabbitmq_host }}\""

- name: "install app dependencies"
  pip:
    requirements: "{{ user_directory }}/{{ app_name }}/requirements.txt"
    virtualenv: "{{ user_directory }}/env"
