---

- name: "create python package directory"
  file:
    path: "{{ user_directory }}/car-package"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0700"
    state: "directory"

- name: "copy xebikart sources"
  copy:
    src: "{{ role_path }}/../../../car-package/xebikart"
    dest: "{{ user_directory }}/car-package"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0700"

- name: "copy xebikart setup.py"
  copy:
    src: "{{ role_path }}/../../../car-package/setup.py"
    dest: "{{ user_directory }}/car-package"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0700"

- name: "install xebikart package"
  pip:
    name: "file://{{ user_directory }}/car-package"
    extra_args: "-e"
    virtualenv: "{{ user_directory }}/env"