---

- name: "create directory"
  file:
    path: "{{ user_directory }}/{{ app_name }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0700"
    state: "directory"

- name: "copy sources"
  copy:
    src: "{{ role_path }}/../../../{{ app_name }}/" # ending slash only copies content inside directory, not directory itself
    dest: "{{ user_directory }}/{{ app_name }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0700"
  notify:
    - "restart service"

- name: "apply calibration values"
  lineinfile:
    path: "{{ user_directory }}/{{ app_name }}/config.py"
    regexp: '^{{ item.key }} = '
    line: '{{ item.key }} = {{ item.value }}'
  with_items:
    - key:  "STEERING_LEFT_PWM"
      value: "{{ steering_left_pwm }}"
    - key:  "STEERING_RIGHT_PWM"
      value: "{{ steering_right_pwm }}"
    - key:  "THROTTLE_FORWARD_PWM"
      value: "{{ throttle_forward_pwm }}"
    - key:  "THROTTLE_REVERSE_PWM"
      value: "{{ throttle_reverse_pwm }}"
  notify:
    - "restart service"

- name: "install system dependencies"
  apt:
    name: {{item}}
    update_cache: "yes"
    state: "present"
  with_items:
    - openmpi-dev
    - libfreetype6-dev
    - libilmbase-dev
    - libopenexr-dev
    - libgstreamer1.0-dev
    - libqtgui4
    - libqttest4

- name: "install app dependencies"
  pip:
    requirements: "{{ user_directory }}/{{ app_name }}/requirements-pi.txt"
    virtualenv: "{{ user_directory }}/env"

- name: "copy service file"
  template:
    src: "{{ app_name }}.service"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    mode: "0644"
  notify:
    - "restart service"

- name: "ensure service is started and enabled"
  systemd:
    name: "{{ app_name }}"
    state: "started"
    enabled: "yes"
