---
- name:
  hostname:
    name: "{{ name }}.local"

- name: "install os packages"
  apt:
    name:
      # setup
      - build-essential
      - python3
      - python3-dev
      - python3-pip
      - python3-numpy
      - python3-picamera
      - python3-pandas
      - python3-rpi.gpio
      - i2c-tools
      - avahi-utils
      - joystick
      - libopenjp2-7-dev
      - libtiff5-dev
      - gfortran
      - libatlas-base-dev
      - libopenblas-dev
      - libhdf5-serial-dev
      - git
      - ntp
      # OpenCV
      - libilmbase-dev
      - libopenexr-dev
      - libgstreamer1.0-dev
      - libjasper-dev
      - libwebp-dev
      - libatlas-base-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libqtgui4
      - libqt4-test
      - python3-opencv
      # IMU
      - python3-smbus
    update_cache: "yes"
    state: "present"

- name: "install python dependencies"
  pip:
    name:
      - virtualenv

- name: "add .bash_aliases file"
  lineinfile:
    path: "{{ user_directory }}/.bash_aliases"
    line: "alias ll='ls -l'"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0644"
    create: "yes"

- name: "install python dependencies in virtualenv"
  pip:
    name:
      - https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.14.0-buster/tensorflow-1.14.0-cp37-none-linux_armv7l.whl
    virtualenv: "{{ user_directory }}/env"

- name: "activate virtualenv"
  lineinfile:
    path: "{{ user_directory }}/.bashrc"
    line: "source {{ user_directory }}/env/bin/activate"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0644"
    create: "yes"
