---
- name:
  hostname:
    name: "{{ name }}"

- name: "add .bash_aliases file"
  copy:
    content: "alias ll='ls -l'"
    dest: "/home/pi/.bash_aliases"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0644"

- name: "install os packages"
  apt:
    name:
      - python-setuptools
      - python3-smbus
    update_cache: "yes"
    state: "present"

